package de.syntax_institut.theveggieapp.data.local

import androidx.room.Entity
import androidx.room.PrimaryKey

/**
 * Data class representing a favorite meal entity in the database.
 *
 * This class maps to a table named `favorite_meals` and contains the meal's name, image URL, and a unique ID.
 *
 * @property idMeal The unique identifier for the meal, automatically generated by the database.
 * @property mealName The name of the meal.
 * @property mealImageURL The URL to the meal's image.
 */

@Entity(tableName = "favorite_meals")
data class FavoriteMeal(

    @PrimaryKey(autoGenerate = true)
    val idMeal: Int = 0,

    val mealName: String = "",
    val mealImageURL: String = ""
)